### ISSUE TITLE
Rewriting DiscordTel

### ISSUE THREAD

**Issue by Keanu73** [austinhuang0131/discordtel#50]
The code currently is stuffed in a single index.js file, which makes it more harder to maintain.
My plan is to use a command handler and then do it that way.

**Comment by austinhuang0131** [comment]
if u write the handler first then i'll write the commands

**Comment by Keanu73** [comment]
i already wrote it u dingus
it's index.js.new

**Comment by austinhuang0131** [comment]
i dare u to call me dingus again

**Comment by NubbyTM** [comment]
Is there a branch for this or something? (or is this just a meme)

austin is **NOT** a dingus.

**Comment by Keanu73** [comment]
There is a branch yes.

**Comment by austinhuang0131** [comment]
because i made it u dingus

**Comment by SunburntRock89** [comment]
Why not allow for async and await in the command handler? Pretty simple to implement

**Comment by SunburntRock89** [comment]
~~Add MongoDB support~~

**Comment by austinhuang0131** [comment]
we might use rethonkdb

also why async/await

**Comment by SunburntRock89** [comment]
Why not async/await? If the functionality is there why not use it?

**Comment by SunburntRock89** [comment]
As for Rethink, I don't really see the point. Just another NoSQL DB but this time with a heavy GUI layered on top. There's also the fact that rethink is no longer developed. https://rethinkdb.com/blog/rethinkdb-shutdown/

**Comment by SunburntRock89** [comment]
hey, you should turn this into a PR with a label of "Do not pull"

**Comment by SunburntRock89** [comment]
Oh yeah BTW if you use Mongo make sure to use Mongoose dependency and not MongoDB.

**Comment by Keanu73** [comment]
?

**Comment by SunburntRock89** [comment]
If you decide to use MongoDB, use the wrapper called Mongoose and not MongoDB

**Comment by Keanu73** [comment]
why use MongoDB 🤔

**Comment by SunburntRock89** [comment]
Because rethink is dead lol

**Comment by Keanu73** [comment]
but what about mysql or redis

**Comment by austinhuang0131** [comment]
ew mysql

**Comment by Keanu73** [comment]
ikr

**Comment by SunburntRock89** [comment]
MySql, in JS, kill me

**Comment by Keanu73** [comment]
irkr

**Comment by KingDGrizzle** [comment]
No.

**Comment by SunburntRock89** [comment]
Probs just easiest to use mongo

**Comment by Keanu73** [comment]
King Duchie Grizzle 😎

**Comment by KingDGrizzle** [comment]
Please, I'm almost done >.>

**Comment by SunburntRock89** [comment]
X-Post from a DM Converstation

Eslint: Nun
Using var
That command handler: Please.
still using JSON.parse(fs.readFileSync)
Not having JSON files in a special folder
> Guild.defaultChannel
not defining that using the new d.js structure system in master v12.0
Use mongoose with promises, its awesome!
You should REALLY not disable that many events, just TYPING_START and MESSAGE_DELETE_BULK

Restify? :eyes: 

No. async.

Setting the presence every time you join or leave a guild (btw, theres bot.guilds.size, no need to .array it ;))
more var
Using request instead of snekfetch (do you know how many fucking dependencies that brings (trust me its bad))
Posting can be made into one module to aleviate copy paste
That command handler: No. Use Klasa or something (I can do that :GWbinMmlol: )
support = user_id => bot.guilds.get('281815661317980160').roles.get('281815839936741377').members.map(member => member.id).indexOf(user_id) > -1;

About ^, that can be done in 
 support: userID => bot.guilds.get("ID").roles.get("ROLEID").members.has(userID)


You should really modularize the logging to that set channel

Those emojis can be also saved in a constants file
Creating invites without perms? :GWbowsuBlobThinkOwO: (More like without the users agreement)
blacklist should really be a module! and / or a DB
Daily is.. can be better
That phone book tho. Fuck me, a db would help ;)
Just: This https://github.com/austinhuang0131/discordtel/blob/rewrite/commands/help.js
And this https://github.com/austinhuang0131/discordtel/blob/rewrite/commands/info.js
E M B E D S
ARE YOU SURE ABOUT THAT?** I'M NOT LETTING YOU BREAK THE ECONOMY! YES I'M FUCKING SURE (this i find funny xd)
Hardcoding IDs instead of saving them in a JSON file

Thats all me thinks(edited)

**Comment by SunburntRock89** [comment]
https://cdn.discordapp.com/attachments/217998227025297408/392783786452058112/unknown.png

**Comment by SunburntRock89** [comment]
![https://cdn.discordapp.com/attachments/217998227025297408/392783786452058112/unknown.png]

**Comment by SunburntRock89** [comment]
![]https://cdn.discordapp.com/attachments/217998227025297408/392783786452058112/unknown.png

**Comment by austinhuang0131** [comment]
* fuck eslint
* i'll use const for fixed variabled but i'm not using let
* handler was from https://anidiots.guide
* `require("something.json")` i think it only loads once
* fine
* ok
* the key reason why we use rethink is because we installed rethink before rom took away my sudo
* it doesn't really matter
* :eyes:
* why async
* why not, it reflects real time change. also ok
* no request is good
* wdym "posting can be made into one module"
* i said it was from an idiot's guide
* ok
* ok
* why
* this is in our [tos compliance](http://discordtel.readthedocs.io/en/latest/ToS%20Compliance/) and we show this every time someone adds discordtel
* how
* ok
* ok
* ok
* why make ripping the bot off easier

**Comment by ibemember3** [comment]
ok

**Comment by babdab9** [comment]
can we kill this issu?

**Comment by Keanu73** [comment]
doubt its finished yet

**Comment by babdab9** [comment]
**we dont need it, we have #rewrite-nots (where hereby I ask for access)

**Comment by SunburntRock89** [comment]
well, no, you can't have access, you haven't even committed anything

**Comment by SunburntRock89** [comment]
This is soooo close to done its unbelievable
