### ISSUE TITLE
Add order command back?

### ISSUE THREAD

**Issue by Keanu73** [austinhuang0131/discordtel#83]
I mean, we're only at ~400 servers so we should add it back.
Here's my plan for when we need to shard:
Communicating shards. So we'll have a channel. Say if someone from shard 0 wants to dial someone in shard 1. They'll dial, it'll go through the channel, which then shard 1 gets it and picks it up, and then transmits the messages back and forth. For the order function.. we don't need to do anything. Since it all goes to the #order channel and then no problem.

**Comment by ytMrTNT** [comment]
I don't know what a shard is, but this is a Telephone bot, not a Discord Pizza or Donuts bot is it? I feel there is no point bringing back the Order command, because it isn't a Discord Restaurant, it is a Discord Telephone Service.

**Comment by Keanu73** [comment]
We'll have an integration with Discord Donuts..

**Comment by KingDGrizzle** [comment]
That is the worst way to handle communication between shards, and it won't even work. I can explain more on Discord, as it's very technical

**Comment by ytMrTNT** [comment]
Why Discord Donuts?
I thought it was ded

**Comment by Keanu73** [comment]
@KingDGrizzle tell me then

**Comment by SunburntRock89** [comment]
do it

**Comment by deodev** [comment]
Hell yeah man, also maybe bring back restaurant workers applications?

**Comment by iilukas** [comment]
Upvote!

**Comment by iilukas** [comment]
Make it come back now.

**Comment by iilukas** [comment]
Discord Donuts and Discord Pizza are both dead and this could be the new Discord TeleOrder lol.

**Comment by Tempestius** [comment]
Yeah, it’d probably be in our best interest. I’ll talk to the executives about it

**Comment by austinhuang0131** [comment]
I mean we might allow other people to operate restaurants on dtel to decrease our own load

* Authorized Restaurants are listed on `>order`
* On `>order` you choose a restaurant and describe order and it gets posted in the Restaurant channel
* They'll just click invite to deliver

**Comment by Tempestius** [comment]
ur lazy

**Comment by iilukas** [comment]
Use the open source bot Discord Donuts with S’more Software as a reference....

**Comment by austinhuang0131** [comment]
@iilukas Sounds like you're smart, eh? I know how to code this, I just don't want to add another database while the bot is already struggling with memory issues.

I don't want restaurant back because...

* It has already been through the consequences of market saturation. DD and DP (1st version) all died, and there is a reason that this trend went silent for a long time. Yes, people are starting them up again, but eventually the cycle will repeat and the history will happen again.
* HR management is heavy work. While DiscordTel used ideas from Roblox (which has many simulators, which I started to believe that simulating phone calls is fun, which lead to DTel), I don't want to be like an actual Roblox game/group. We only hire few CSs and it's already challenging to calm these triggering candidates down.
* Nothing supports the claim that it increases server count.

**Comment by SunburntRock89** [comment]
The bot is not struggling. Errors in your code are causing out of memory issues when they are not correct. The database has been unaffected.

**Comment by iilukas** [comment]
^ Upvote on the comment Sunburnt referred to. The memory issues are because your code is written bad.

**Comment by austinhuang0131** [comment]
> @SunburntRock89 : "u wrote bad code"
>
> "i second this"

Lukas just stop, you can't comment without knowing the situation, if you are being silly again I'll consider my options

**Comment by SunburntRock89** [comment]
What situation? You wrote bad code and that's that

**Comment by austinhuang0131** [comment]
yeah but i didn't have runtime logs so i can't know where I did wrong

**Comment by SunburntRock89** [comment]
Yes but I sent you them.

**Comment by iilukas** [comment]
oh snap. something went down....

**Comment by Keanu73** [comment]
maybe give ownership to sunburntrock becuz he know how to code Beter than you :^)

**Comment by cfanoulis** [comment]
LIKE FUCKING YES PLEASE

**Comment by Rexogamer** [comment]
rip this

**Comment by cfanoulis** [comment]
tbh thinking about just PRing it :omegalul:
